[package]
name = "ldk-lsp-client"
version = "0.1.0"
authors = ["Elias Rohrer <dev@tnull.de>"]
edition = "2018"
description = "Types and primitives to integrate a spec-compliant LSP with an LDK-based node."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = { version = "0.0.114", features = ["max_level_trace", "std"] }
lightning-invoice = { version = "0.22" }
lightning-net-tokio = { version = "0.0.114" }

bitcoin = "0.29.2"
