[package]
name = "ldk-lsp-client"
version = "0.1.0"
authors = ["Elias Rohrer <dev@tnull.de>"]
edition = "2018"
description = "Types and primitives to integrate a spec-compliant LSP with an LDK-based node."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = { git = "https://github.com/lightningdevkit/rust-lightning.git", rev = "a358ba2e68c84d19e70d1d45d3f677eaf324e09d", features = ["max_level_trace", "std"] }
lightning-invoice = { git = "https://github.com/lightningdevkit/rust-lightning.git", rev = "a358ba2e68c84d19e70d1d45d3f677eaf324e09d" }
lightning-net-tokio = { git = "https://github.com/lightningdevkit/rust-lightning.git", rev = "a358ba2e68c84d19e70d1d45d3f677eaf324e09d" }

bitcoin = "0.29.0"

serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0"
