name: Continuous Integration Checks

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain: [ stable, beta ]
        include:
          - toolchain: stable
            check-fmt: true
          - toolchain: 1.63.0
            platform: ubuntu-latest
            msrv: true

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
      - name: Pin crates for MSRV
        if: matrix.msrv
        run: |
          # No need to pin currently
      - name: Cargo check
        run: cargo check --release
      - name: Check documentation
        run: cargo doc --release
      - name: Build on Rust ${{ matrix.toolchain }}
        run: cargo build --verbose --color always
      - name: Check formatting
        if: matrix.check-fmt
        run: rustup component add rustfmt && cargo fmt --all -- --check
      - name: Test on Rust ${{ matrix.toolchain }}
        run: cargo test
      - name: Test on Rust ${{ matrix.toolchain }} with LSPS1 support
        run: RUSTFLAGS="--cfg lsps1" cargo test
